# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-14 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostsSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('product_image', models.ImageField(upload_to='pic_folder/')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 12, 14, 7, 19, 28, 713161, tzinfo=utc))),
            ],
        ),
    ]
