# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 14, 7, 37, 36, 145017, tzinfo=utc)),
        ),
    ]
