# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20161214_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 14, 13, 3, 47, 362652, tzinfo=utc)),
        ),
    ]
