# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20161214_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 14, 16, 50, 22, 240413, tzinfo=utc)),
        ),
    ]
