# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20161215_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postssubmit',
            name='product_image',
        ),
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 4, 24, 49, 896187, tzinfo=utc)),
        ),
    ]
