# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20161215_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='postssubmit',
            name='product_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 4, 30, 6, 312982, tzinfo=utc)),
        ),
    ]
