# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20161215_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 4, 56, 40, 799186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postssubmit',
            name='product_image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
