# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20161215_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postssubmit',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 5, 35, 44, 990022, tzinfo=utc)),
        ),
    ]
