# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20161215_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postssubmit',
            name='product_image',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
