# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20161215_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='postssubmit',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='postssubmit',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbs/'),
            preserve_default=False,
        ),
    ]
